import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { isAbsolute, join, relative, sep } from "node:path";
import { test } from "node:test";
import { createTestWorkspace, FIXTURES } from "@helmlock/core/testing";
import { catalog } from "@helmlock/plugins";
import { frontmatter, parseYaml } from "./frontmatter.ts";
import { generate, hlArgs, LOCK_FILE } from "./generate.ts";
import { LCWMS_LINT, lintHarness } from "./lint.ts";
import { loadLayers, loadSource } from "./source.ts";
import { syncHarness } from "./sync.ts";

const GOLDEN = join(FIXTURES, "s5-harness-golden");

/** <tmp>/ws holds the fixture; <tmp>/delivery is a sibling delivery repo with no harness source (workspace layer only). */
function copyFixture(name: string): string {
  const base = mkdtempSync(join(tmpdir(), `hl-${name}-`));
  const root = join(base, "ws");
  cpSync(join(FIXTURES, name), root, { recursive: true });
  mkdirSync(join(base, "delivery"));
  return root;
}
const dlv = (root: string) => join(root, "..", "delivery");

test("golden outputs for both hosts from the fixture harness.toml (delivery repo without a source)", () => {
  const root = copyFixture("s5-harness");
  try {
    const res = syncHarness(root, dlv(root));
    assert.deepEqual(
      res.map((r) => `${r.status} ${r.path}`),
      [
        "written .claude/settings.json",
        "written .mcp.json",
        "written .cursor/hooks.json",
        "written .cursor/cli.json",
        "written .cursor/mcp.json",
        "written .cursor/rules/helmlock.mdc",
        "written .cursorignore",
        "written AGENTS.md",
        `written ${LOCK_FILE}`,
      ],
    );
    for (const r of res) {
      const got = readFileSync(join(root, r.path), "utf8");
      const goldenFile = join(GOLDEN, r.path);
      if (process.env.HL_UPDATE_GOLDEN) {
        mkdirSync(join(goldenFile, ".."), { recursive: true });
        writeFileSync(goldenFile, got);
      }
      assert.equal(got, readFileSync(goldenFile, "utf8").replace(/\r\n/g, "\n"), r.path);
    }
    // a second sync changes nothing; --check is clean
    assert.ok(syncHarness(root, dlv(root)).every((r) => r.status === "unchanged"));
    assert.ok(syncHarness(root, dlv(root), { check: true }).every((r) => r.status === "unchanged"));
  } finally {
    rmSync(join(root, ".."), { recursive: true, force: true });
  }
});

test("generated files: Claude JSON stamped inline, hooks once per host, AGENTS.md text outside the block kept", () => {
  const root = copyFixture("s5-harness");
  try {
    syncHarness(root, dlv(root));
    const settings = JSON.parse(readFileSync(join(root, ".claude/settings.json"), "utf8"));
    assert.match(settings["//"], /^GENERATED by hl harness sync [0-9a-f]{12}/);
    assert.deepEqual(settings.permissions.deny.slice(0, 2), ["Edit(artifacts/**/ticket.toml)", "Edit(logs/**)"]);
    assert.ok(settings.permissions.deny.includes("Read(.env)"));
    assert.deepEqual(settings.permissions.ask, ["Bash(git push:*)", "Bash(gh pr merge:*)"]);
    assert.equal(settings.hooks.PostToolUse[0].matcher, "Edit|Write");
    assert.match(
      settings.hooks.SessionStart[0].hooks[0].command,
      /^node "\$CLAUDE_PROJECT_DIR\/\.\.\/delivery\/packages\/plugins\/harness\/hooks\/session-start\.ts" --host claude -- context --session$/,
    );
    const cursor = JSON.parse(readFileSync(join(root, ".cursor/hooks.json"), "utf8"));
    assert.equal(cursor.version, 1);
    assert.deepEqual(Object.keys(cursor.hooks), ["sessionStart", "afterFileEdit", "stop"]);
    for (const list of Object.values(cursor.hooks) as { command: string }[][]) {
      assert.equal(list.length, 1);
      assert.match(list[0]?.command ?? "", /--host cursor/);
    }
    assert.ok(!("//" in cursor), "Cursor JSON carries no inline key; the lock stamps it");
    const agents = readFileSync(join(root, "AGENTS.md"), "utf8");
    assert.match(agents, /^# Fixture rulebook\n\nHand-written text above the block stays\.\n\n<!-- hl:generated:start -->\n<!-- GENERATED/);
    assert.match(agents, /## Core rules[\s\S]*\n\n## Using the hl CLI[\s\S]*<!-- hl:generated:end -->\n\nHand-written text below the block stays too\.\n$/);
    assert.ok(!agents.includes("old generated text"));
    assert.match(readFileSync(join(root, ".cursor/rules/helmlock.mdc"), "utf8"), /^---\ndescription: .*\nalwaysApply: true\n---\n/);
  } finally {
    rmSync(join(root, ".."), { recursive: true, force: true });
  }
});

test("--check reports stale after the source changes or a generated file is edited, missing when deleted", () => {
  const root = copyFixture("s5-harness");
  try {
    syncHarness(root, dlv(root));
    const status = () => Object.fromEntries(syncHarness(root, dlv(root), { check: true }).map((r) => [r.path, r.status]));
    // hand edit of one generated file
    writeFileSync(join(root, ".cursorignore"), "edited by hand\n");
    assert.equal(status()[".cursorignore"], "stale");
    // hand-written AGENTS.md text outside the block is not staleness
    writeFileSync(join(root, "AGENTS.md"), readFileSync(join(root, "AGENTS.md"), "utf8").replace("stays too", "stays, edited"));
    assert.equal(status()["AGENTS.md"], "unchanged");
    syncHarness(root, dlv(root));
    // source edit: every stamped file goes stale
    writeFileSync(join(root, "harness/harness.toml"), readFileSync(join(root, "harness/harness.toml"), "utf8").replace('"_work/"', '"_work/", "tmp/"'));
    const s = status();
    assert.equal(s[".cursorignore"], "stale");
    assert.equal(s[".claude/settings.json"], "stale");
    assert.equal(s[LOCK_FILE], "stale");
    rmSync(join(root, ".cursor/cli.json"));
    assert.equal(status()[".cursor/cli.json"], "missing");
    // check wrote nothing
    assert.ok(!existsSync(join(root, ".cursor/cli.json")));
  } finally {
    rmSync(join(root, ".."), { recursive: true, force: true });
  }
});

test("a delivery repo outside the synced root: absolute hook paths across drives, else project-relative; no mcp means no mcp files; AGENTS.md created", () => {
  const root = copyFixture("s5-harness");
  try {
    rmSync(join(root, "AGENTS.md"));
    writeFileSync(join(root, "harness/harness.toml"), readFileSync(join(root, "harness/harness.toml"), "utf8").replace(/\[\[mcp\]\][\s\S]*$/, ""));
    const src = loadSource(root);
    // Outside the synced root. On Windows another drive has no relative path, so the hook path is absolute; on one
    // filesystem (Linux, macOS) it stays relative to the project.
    const delivery = process.platform === "win32" ? "D:/delivery" : "/opt/delivery";
    const files = generate(src, { deliveryRoot: delivery });
    assert.ok(!files.some((f) => f.path.endsWith("mcp.json")));
    const settings = JSON.parse(files.find((f) => f.path === ".claude/settings.json")?.content ?? "{}");
    const rel = relative(root, delivery);
    const script = isAbsolute(rel) ? delivery : `$CLAUDE_PROJECT_DIR/${rel.split(sep).join("/")}`;
    assert.equal(
      settings.hooks.Stop[0].hooks[0].command,
      `node "${script}/packages/plugins/harness/hooks/stop.ts" --host claude --policy harness/harness.toml -- log show`,
    );
    assert.match(files.find((f) => f.path === "AGENTS.md")?.content ?? "", /^<!-- hl:generated:start -->\n/);
    assert.deepEqual(hlArgs('hl log-work - "two words"'), ["log-work", "-", "two words"]);
  } finally {
    rmSync(join(root, ".."), { recursive: true, force: true });
  }
});

test("a ladder with 'default' is rejected", () => {
  const root = copyFixture("s5-harness");
  try {
    writeFileSync(join(root, "harness/harness.toml"), '[modes]\nladder = ["plan", "default"]\n');
    assert.throws(() => loadSource(root), /must not contain 'default'/);
  } finally {
    rmSync(join(root, ".."), { recursive: true, force: true });
  }
});

/** <tmp>/helmlock (system layer) and <tmp>/acme (workspace layer), siblings on one drive. */
function copyLayers(): { base: string; delivery: string; root: string } {
  const base = mkdtempSync(join(tmpdir(), "hl-layers-"));
  const delivery = join(base, "helmlock");
  const root = join(base, "acme");
  cpSync(join(FIXTURES, "s5-layers", "delivery"), delivery, { recursive: true });
  cpSync(join(FIXTURES, "s5-layers", "knowledge"), root, { recursive: true });
  return { base, delivery, root };
}

test("knowledge repo: system and workspace layers merge (system first) into both hosts' config", () => {
  const { base, delivery, root } = copyLayers();
  try {
    syncHarness(root, delivery);
    const settings = JSON.parse(readFileSync(join(root, ".claude/settings.json"), "utf8"));
    assert.deepEqual(settings.permissions.deny, [
      "Edit(artifacts/**/ticket.toml)",
      "Edit(logs/**)",
      "Edit(secrets/**)",
      "Read(.env)",
      "Read(_work/**)",
      "Read(author.local)",
      "Read(*.local.toml)",
      "Bash(rm -rf:*)",
    ]);
    assert.deepEqual(settings.permissions.ask, ["Bash(git push:*)", "Bash(npm publish:*)"]);
    const hooks = "$CLAUDE_PROJECT_DIR/../helmlock/packages/plugins/harness/hooks";
    const cmds = (ev: string) => (settings.hooks[ev] as { hooks: { command: string }[] }[]).map((g) => g.hooks[0]?.command);
    assert.deepEqual(cmds("SessionStart"), [
      `node "${hooks}/session-start.ts" --host claude -- context --session`,
      `node "${hooks}/session-start.ts" --host claude -- where`,
    ]);
    assert.deepEqual(cmds("PostToolUse"), [`node "${hooks}/post-edit.ts" --host claude -- validate --changed`], "identical hook deduped");
    assert.deepEqual(cmds("Stop"), [
      `node "${hooks}/stop.ts" --host claude --policy ../helmlock/harness/harness.toml --policy harness/harness.toml -- log show`,
    ]);
    const cursor = JSON.parse(readFileSync(join(root, ".cursor/hooks.json"), "utf8"));
    assert.equal(cursor.hooks.afterFileEdit[0].command, `node "../helmlock/packages/plugins/harness/hooks/post-edit.ts" --host cursor -- validate --changed`);
    assert.equal(cursor.hooks.beforeShellExecution, undefined); // opt-in only, see generate.ts
    // mcp: workspace wins on the same name; ignore: union
    assert.deepEqual(JSON.parse(readFileSync(join(root, ".mcp.json"), "utf8")).mcpServers.helmlock.args, ["other.ts"]);
    assert.match(readFileSync(join(root, ".cursorignore"), "utf8"), /\narchive\/\n_work\/\nruns\/\*\*\n$/);
    // Cursor gets the system AGENTS.md (without its block) then the merged rules; README.md is not a rule
    const mdc = readFileSync(join(root, ".cursor/rules/helmlock.mdc"), "utf8");
    assert.match(mdc, /# Fixture system rulebook\n\nSystem gate: GROUND before drafting anything\.\n\n## System core rules\n[\s\S]*## Workspace rules\n/);
    assert.ok(!mdc.includes("old system block") && !mdc.includes("Not a rule"));
    // the knowledge AGENTS.md block carries the merged rules, not the whole system AGENTS.md
    const agents = readFileSync(join(root, "AGENTS.md"), "utf8");
    assert.match(
      agents,
      /^# Fixture knowledge center\n\nHand-written text stays\.\n\n<!-- hl:generated:start -->[\s\S]*## System core rules[\s\S]*## Workspace rules[\s\S]*<!-- hl:generated:end -->\n$/,
    );
    assert.ok(!agents.includes("System gate"));
    assert.ok(syncHarness(root, delivery, { check: true }).every((r) => r.status === "unchanged"));
    // a change in either layer makes --check stale
    const stale = () =>
      syncHarness(root, delivery, { check: true })
        .filter((r) => r.status === "stale")
        .map((r) => r.path);
    writeFileSync(join(delivery, "harness/rules/10-core.md"), "## System core rules\n\n- Changed.\n");
    assert.ok(stale().includes(".claude/settings.json"));
    syncHarness(root, delivery);
    writeFileSync(
      join(root, "harness/harness.toml"),
      readFileSync(join(root, "harness/harness.toml"), "utf8").replace('"secrets/**"', '"secrets/**", "keys/**"'),
    );
    assert.ok(stale().includes(".claude/settings.json"));
    syncHarness(root, delivery);
    writeFileSync(join(delivery, "AGENTS.md"), readFileSync(join(delivery, "AGENTS.md"), "utf8").replace("GROUND", "SURVEY"));
    assert.ok(stale().includes(".cursor/rules/helmlock.mdc"));
  } finally {
    rmSync(base, { recursive: true, force: true });
  }
});

test("modes: the workspace may set default, the ladder stays the system's; lint not_skills union", () => {
  const { base, delivery, root } = copyLayers();
  try {
    assert.equal(loadLayers(root, delivery).toml.modes.default, "plan");
    writeFileSync(
      join(root, "harness/harness.toml"),
      `${readFileSync(join(root, "harness/harness.toml"), "utf8")}\n[modes]\ndefault = "ask"\n\n[lint]\nnot_skills = ["x"]\n`,
    );
    const t = loadLayers(root, delivery).toml;
    assert.equal(t.modes.default, "ask");
    assert.deepEqual(t.modes.ladder, ["plan", "ask", "auto-review", "force"]);
    assert.deepEqual(t.lint.not_skills, ["plan-board", "x"]);
  } finally {
    rmSync(base, { recursive: true, force: true });
  }
});

test("sync in the delivery repo writes only the AGENTS.md block", () => {
  const { base, delivery } = copyLayers();
  try {
    const res = syncHarness(delivery, delivery);
    assert.deepEqual(
      res.map((r) => `${r.status} ${r.path}`),
      ["written AGENTS.md"],
    );
    assert.ok(!existsSync(join(delivery, ".claude")) && !existsSync(join(delivery, ".cursor")) && !existsSync(join(delivery, ".cursorignore")));
    const agents = readFileSync(join(delivery, "AGENTS.md"), "utf8");
    assert.match(agents, /System gate[\s\S]*<!-- hl:generated:start -->[\s\S]*## System core rules/);
    assert.deepEqual(
      syncHarness(delivery, delivery, { check: true }).map((r) => `${r.status} ${r.path}`),
      ["unchanged AGENTS.md"],
    );
  } finally {
    rmSync(base, { recursive: true, force: true });
  }
});

test("hl harness sync / --check / lint through the verb registry", async () => {
  const ws = await createTestWorkspace({ catalog });
  try {
    cpSync(join(FIXTURES, "s5-harness", "harness"), join(ws.root, "harness"), { recursive: true });
    const check1 = await ws.run("harness sync", { check: true });
    assert.equal(check1.ok, false);
    assert.equal(!check1.ok && check1.error.rule, "harness-stale");
    const sync = await ws.run("harness sync", {});
    assert.ok(sync.ok);
    assert.ok(existsSync(join(ws.root, ".cursor", "hooks.json")));
    const check2 = await ws.run("harness sync", { check: true });
    assert.ok(check2.ok);
    const lint = await ws.run("harness lint", {});
    assert.ok(lint.ok, JSON.stringify(lint));
    const svc = ws.runtime.ctx.get("harness");
    assert.deepEqual(await svc.lint({ root: join(FIXTURES, "s5-lint") }).then((f) => f.filter((x) => x.level === "error").length), 18);
  } finally {
    await ws.cleanup();
  }
});

// ---------- lint (ported from harness_lint.py and test_skill_contract.py)

test("lint fixture: every rule fires once where expected", () => {
  const f = lintHarness(join(FIXTURES, "s5-lint"));
  const key = (x: { level: string; rule: string; file?: string }) => `${x.level} ${x.rule} ${x.file}`;
  assert.deepEqual(f.map(key).sort(), [
    "error lint:agent-format .claude/agents/broken.md",
    "error lint:agent-frontmatter .claude/agents/broken.md",
    "error lint:agent-frontmatter .claude/agents/broken.md",
    "error lint:command CLAUDE.md",
    "error lint:description .claude/skills/short-desc/SKILL.md",
    "error lint:frontmatter .claude/skills/no-front/SKILL.md",
    "error lint:frontmatter .claude/skills/unclosed/SKILL.md",
    "error lint:hidden-skill .claude/skills/hidden",
    "error lint:hook-script .claude/settings.json",
    "error lint:hook-script .cursor/hooks.json",
    "error lint:not-a-skill .claude/skills/empty-folder",
    "error lint:path CLAUDE.md",
    "error lint:skill-format .claude/skills/wrong-sections/SKILL.md",
    "error lint:skill-length .claude/skills/too-long/SKILL.md",
    "error lint:skill-name .claude/skills/bad-name/SKILL.md",
    "error lint:trigger .claude/skills/no-trigger/SKILL.md",
    "error lint:vendored-drift .claude/skills/vendored-one/extra.md",
    "error lint:version-footer .claude/skills/versioned/SKILL.md",
    "warn lint:orphan .claude/skills/hidden",
    "warn lint:orphan .claude/skills/vendored-one",
  ]);
  const msgs = f.map((x) => x.message).join("\n");
  assert.match(msgs, /path does not exist: \.claude\/skills\/nope\/SKILL\.md/);
  assert.match(msgs, /command resolves to no skill or alias: \/ghost/);
  assert.doesNotMatch(msgs, /missing-from-evals|\/fold\b|\/loop|<name>/);
});

test("lint: a missing path is an error unless git ignores it (generated outputs may be absent on a fresh clone)", () => {
  const root = mkdtempSync(join(tmpdir(), "hl-lint-ignored-"));
  try {
    execFileSync("git", ["init", "-q"], { cwd: root });
    writeFileSync(join(root, ".gitignore"), "docs/generated.html\n");
    writeFileSync(join(root, "CLAUDE.md"), "# Rules\n\nRead `docs/missing.md`; the page `docs/generated.html` is built locally.\n");
    const msgs = lintHarness(root, { pathPrefixes: ["docs/"] })
      .map((x) => x.message)
      .join("\n");
    assert.match(msgs, /path does not exist: docs\/missing\.md/);
    assert.doesNotMatch(msgs, /generated\.html/);
  } finally {
    rmSync(root, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 });
  }
});

test("frontmatter: folded block, quoted strings, nested aliases list, flow list", () => {
  const { data, body } = frontmatter(
    '---\r\nname: "a: b"\r\ndescription: >\r\n  one\r\n  two\r\ntools: [Read, Edit]\r\nmetadata:\r\n  aliases:\r\n    - x\r\n    - "/y"\r\n---\r\nBODY',
  );
  assert.deepEqual(data, { name: "a: b", description: "one two", tools: ["Read", "Edit"], metadata: { aliases: ["x", "/y"] } });
  assert.equal(body, "\nBODY");
  assert.deepEqual(parseYaml("k: plain value\n  continued"), { k: "plain value continued" });
});

const LCWMS = "D:/Workspace/research-workspace/lc-wms-cursor-config/lc-wms-cursor-config";
test("lc-wms comparison: same findings per file as harness_lint.py (paths, commands, orphans)", {
  skip: !existsSync(LCWMS) && "lc-wms repo not on this machine",
}, () => {
  // Recorded from `python .kanban/core/harness_lint.py` on 2026-10-07: 46 errors, 2 warnings; the 7 "project skill
  // id" errors come from an lc-wms-only registry check that is not ported.
  const expected = JSON.parse(readFileSync(join(FIXTURES, "s5-lint-lcwms.json"), "utf8")) as {
    errors: { where: string; message: string }[];
    warnings: unknown[];
  };
  const ported = expected.errors.filter((e) => !e.message.startsWith("project skill id"));
  const got = lintHarness(LCWMS, LCWMS_LINT);
  const norm = (xs: { where?: string; file?: string; message: string }[]) => xs.map((x) => `${x.where ?? x.file}: ${x.message}`).sort();
  assert.deepEqual(norm(got.filter((g) => g.level === "error")), norm(ported));
  assert.equal(got.filter((g) => g.level === "warn").length, expected.warnings.length);
});

test("knowledge repo: system agents are copied into .claude/agents with a GENERATED note after the frontmatter", async () => {
  const { stampAgent } = await import("./generate.ts");
  const out = stampAgent("---\nname: builder\ndescription: x\n---\nBody\n", "abc");
  assert.match(out, /^---\nname: builder\ndescription: x\n---\n<!-- GENERATED by hl harness sync abc/);
  assert.match(out, /Body\n$/);
});
