import assert from "node:assert/strict";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { createTestWorkspace, FIXTURES } from "@helmlock/core/testing";
import { catalog } from "@helmlock/plugins";
import { frontmatter, parseYaml } from "./frontmatter.ts";
import { generate, hlArgs, LOCK_FILE } from "./generate.ts";
import { LCWMS_LINT, lintHarness } from "./lint.ts";
import { loadSource } from "./source.ts";
import { syncHarness } from "./sync.ts";

const GOLDEN = join(FIXTURES, "s5-harness-golden");

function copyFixture(name: string): string {
  const dir = mkdtempSync(join(tmpdir(), `hl-${name}-`));
  cpSync(join(FIXTURES, name), dir, { recursive: true });
  return dir;
}

test("golden outputs for both hosts from the fixture harness.toml (delivery = the synced repo)", () => {
  const root = copyFixture("s5-harness");
  try {
    const res = syncHarness(root, root);
    assert.deepEqual(
      res.map((r) => `${r.status} ${r.path}`),
      [
        "written .claude/settings.json",
        "written .mcp.json",
        "written .cursor/hooks.json",
        "written .cursor/cli.json",
        "written .cursor/mcp.json",
        "written .cursor/rules/helmlock.mdc",
        "written .cursorignore",
        "written AGENTS.md",
        `written ${LOCK_FILE}`,
      ],
    );
    for (const r of res) {
      const got = readFileSync(join(root, r.path), "utf8");
      const goldenFile = join(GOLDEN, r.path);
      if (process.env.HL_UPDATE_GOLDEN) {
        mkdirSync(join(goldenFile, ".."), { recursive: true });
        writeFileSync(goldenFile, got);
      }
      assert.equal(got, readFileSync(goldenFile, "utf8").replace(/\r\n/g, "\n"), r.path);
    }
    // a second sync changes nothing; --check is clean
    assert.ok(syncHarness(root, root).every((r) => r.status === "unchanged"));
    assert.ok(syncHarness(root, root, { check: true }).every((r) => r.status === "unchanged"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("generated files: Claude JSON stamped inline, hooks once per host, AGENTS.md text outside the block kept", () => {
  const root = copyFixture("s5-harness");
  try {
    syncHarness(root, root);
    const settings = JSON.parse(readFileSync(join(root, ".claude/settings.json"), "utf8"));
    assert.match(settings["//"], /^GENERATED by hl harness sync [0-9a-f]{12}/);
    assert.deepEqual(settings.permissions.deny.slice(0, 2), ["Edit(artifacts/**/ticket.toml)", "Write(artifacts/**/ticket.toml)"]);
    assert.ok(settings.permissions.deny.includes("Read(.env)"));
    assert.deepEqual(settings.permissions.ask, ["Bash(git push:*)", "Bash(gh pr merge:*)"]);
    assert.equal(settings.hooks.PostToolUse[0].matcher, "Edit|Write");
    assert.match(
      settings.hooks.SessionStart[0].hooks[0].command,
      /^node "\$CLAUDE_PROJECT_DIR\/packages\/plugins\/harness\/hooks\/session-start\.ts" --host claude -- context --session$/,
    );
    const cursor = JSON.parse(readFileSync(join(root, ".cursor/hooks.json"), "utf8"));
    assert.equal(cursor.version, 1);
    assert.deepEqual(Object.keys(cursor.hooks), ["sessionStart", "afterFileEdit", "stop", "beforeShellExecution"]);
    for (const list of Object.values(cursor.hooks) as { command: string }[][]) {
      assert.equal(list.length, 1);
      assert.match(list[0]?.command ?? "", /--host cursor/);
    }
    assert.ok(!("//" in cursor), "Cursor JSON carries no inline key; the lock stamps it");
    const agents = readFileSync(join(root, "AGENTS.md"), "utf8");
    assert.match(agents, /^# Fixture rulebook\n\nHand-written text above the block stays\.\n\n<!-- hl:generated:start -->\n<!-- GENERATED/);
    assert.match(agents, /## Core rules[\s\S]*\n\n## Using the hl CLI[\s\S]*<!-- hl:generated:end -->\n\nHand-written text below the block stays too\.\n$/);
    assert.ok(!agents.includes("old generated text"));
    assert.match(readFileSync(join(root, ".cursor/rules/helmlock.mdc"), "utf8"), /^---\ndescription: .*\nalwaysApply: true\n---\n/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("--check reports stale after the source changes or a generated file is edited, missing when deleted", () => {
  const root = copyFixture("s5-harness");
  try {
    syncHarness(root, root);
    const status = () => Object.fromEntries(syncHarness(root, root, { check: true }).map((r) => [r.path, r.status]));
    // hand edit of one generated file
    writeFileSync(join(root, ".cursorignore"), "edited by hand\n");
    assert.equal(status()[".cursorignore"], "stale");
    // hand-written AGENTS.md text outside the block is not staleness
    writeFileSync(join(root, "AGENTS.md"), readFileSync(join(root, "AGENTS.md"), "utf8").replace("stays too", "stays, edited"));
    assert.equal(status()["AGENTS.md"], "unchanged");
    syncHarness(root, root);
    // source edit: every stamped file goes stale
    writeFileSync(join(root, "harness/harness.toml"), readFileSync(join(root, "harness/harness.toml"), "utf8").replace('"_work/"', '"_work/", "tmp/"'));
    const s = status();
    assert.equal(s[".cursorignore"], "stale");
    assert.equal(s[".claude/settings.json"], "stale");
    assert.equal(s[LOCK_FILE], "stale");
    rmSync(join(root, ".cursor/cli.json"));
    assert.equal(status()[".cursor/cli.json"], "missing");
    // check wrote nothing
    assert.ok(!existsSync(join(root, ".cursor/cli.json")));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("a delivery repo outside the synced root gets absolute hook paths; no mcp means no mcp files; AGENTS.md created", () => {
  const root = copyFixture("s5-harness");
  try {
    rmSync(join(root, "AGENTS.md"));
    writeFileSync(join(root, "harness/harness.toml"), readFileSync(join(root, "harness/harness.toml"), "utf8").replace(/\[\[mcp\]\][\s\S]*$/, ""));
    const src = loadSource(root);
    const files = generate(src, { deliveryRoot: "D:/delivery" });
    assert.ok(!files.some((f) => f.path.endsWith("mcp.json")));
    const settings = JSON.parse(files.find((f) => f.path === ".claude/settings.json")?.content ?? "{}");
    assert.match(
      settings.hooks.Stop[0].hooks[0].command,
      /^node "D:\/delivery\/packages\/plugins\/harness\/hooks\/stop\.ts" --host claude --policy harness\/harness\.toml -- log show$/,
    );
    assert.match(files.find((f) => f.path === "AGENTS.md")?.content ?? "", /^<!-- hl:generated:start -->\n/);
    assert.deepEqual(hlArgs('hl log-work - "two words"'), ["log-work", "-", "two words"]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("a ladder with 'default' is rejected", () => {
  const root = copyFixture("s5-harness");
  try {
    writeFileSync(join(root, "harness/harness.toml"), '[modes]\nladder = ["plan", "default"]\n');
    assert.throws(() => loadSource(root), /must not contain 'default'/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("hl harness sync / --check / lint through the verb registry", async () => {
  const ws = await createTestWorkspace({ catalog });
  try {
    cpSync(join(FIXTURES, "s5-harness", "harness"), join(ws.root, "harness"), { recursive: true });
    const check1 = await ws.run("harness sync", { check: true });
    assert.equal(check1.ok, false);
    assert.equal(!check1.ok && check1.error.rule, "harness-stale");
    const sync = await ws.run("harness sync", {});
    assert.ok(sync.ok);
    assert.ok(existsSync(join(ws.root, ".cursor", "hooks.json")));
    const check2 = await ws.run("harness sync", { check: true });
    assert.ok(check2.ok);
    const lint = await ws.run("harness lint", {});
    assert.ok(lint.ok, JSON.stringify(lint));
    const svc = ws.runtime.ctx.get("harness");
    assert.deepEqual(await svc.lint({ root: join(FIXTURES, "s5-lint") }).then((f) => f.filter((x) => x.level === "error").length), 18);
  } finally {
    await ws.cleanup();
  }
});

// ---------- lint (ported from harness_lint.py and test_skill_contract.py)

test("lint fixture: every rule fires once where expected", () => {
  const f = lintHarness(join(FIXTURES, "s5-lint"));
  const key = (x: { level: string; rule: string; file?: string }) => `${x.level} ${x.rule} ${x.file}`;
  assert.deepEqual(f.map(key).sort(), [
    "error lint:agent-format .claude/agents/broken.md",
    "error lint:agent-frontmatter .claude/agents/broken.md",
    "error lint:agent-frontmatter .claude/agents/broken.md",
    "error lint:command CLAUDE.md",
    "error lint:description .claude/skills/short-desc/SKILL.md",
    "error lint:frontmatter .claude/skills/no-front/SKILL.md",
    "error lint:frontmatter .claude/skills/unclosed/SKILL.md",
    "error lint:hidden-skill .claude/skills/hidden",
    "error lint:hook-script .claude/settings.json",
    "error lint:hook-script .cursor/hooks.json",
    "error lint:not-a-skill .claude/skills/empty-folder",
    "error lint:path CLAUDE.md",
    "error lint:skill-format .claude/skills/wrong-sections/SKILL.md",
    "error lint:skill-length .claude/skills/too-long/SKILL.md",
    "error lint:skill-name .claude/skills/bad-name/SKILL.md",
    "error lint:trigger .claude/skills/no-trigger/SKILL.md",
    "error lint:vendored-drift .claude/skills/vendored-one/extra.md",
    "error lint:version-footer .claude/skills/versioned/SKILL.md",
    "warn lint:orphan .claude/skills/hidden",
    "warn lint:orphan .claude/skills/vendored-one",
  ]);
  const msgs = f.map((x) => x.message).join("\n");
  assert.match(msgs, /path does not exist: \.claude\/skills\/nope\/SKILL\.md/);
  assert.match(msgs, /command resolves to no skill or alias: \/ghost/);
  assert.doesNotMatch(msgs, /missing-from-evals|\/fold\b|\/loop|<name>/);
});

test("frontmatter: folded block, quoted strings, nested aliases list, flow list", () => {
  const { data, body } = frontmatter(
    '---\r\nname: "a: b"\r\ndescription: >\r\n  one\r\n  two\r\ntools: [Read, Edit]\r\nmetadata:\r\n  aliases:\r\n    - x\r\n    - "/y"\r\n---\r\nBODY',
  );
  assert.deepEqual(data, { name: "a: b", description: "one two", tools: ["Read", "Edit"], metadata: { aliases: ["x", "/y"] } });
  assert.equal(body, "\nBODY");
  assert.deepEqual(parseYaml("k: plain value\n  continued"), { k: "plain value continued" });
});

const LCWMS = "D:/Workspace/research-workspace/lc-wms-cursor-config/lc-wms-cursor-config";
test("lc-wms comparison: same findings per file as harness_lint.py (paths, commands, orphans)", {
  skip: !existsSync(LCWMS) && "lc-wms repo not on this machine",
}, () => {
  // Recorded from `python .kanban/core/harness_lint.py` on 2026-10-07: 46 errors, 2 warnings; the 7 "project skill
  // id" errors come from an lc-wms-only registry check that is not ported.
  const expected = JSON.parse(readFileSync(join(FIXTURES, "s5-lint-lcwms.json"), "utf8")) as {
    errors: { where: string; message: string }[];
    warnings: unknown[];
  };
  const ported = expected.errors.filter((e) => !e.message.startsWith("project skill id"));
  const got = lintHarness(LCWMS, LCWMS_LINT);
  const norm = (xs: { where?: string; file?: string; message: string }[]) => xs.map((x) => `${x.where ?? x.file}: ${x.message}`).sort();
  assert.deepEqual(norm(got.filter((g) => g.level === "error")), norm(ported));
  assert.equal(got.filter((g) => g.level === "warn").length, expected.warnings.length);
});
