// Agent and skill layers (Blueprint 31). Sources, lowest to highest precedence:
//   system    delivery repo .claude/agents/*.md, .claude/skills/<name>/
//   workspace knowledge repo harness/agents/*.md, harness/skills/<name>/ (committed, shared)
//   personal  knowledge repo people/<author>/agents/*.md, people/<author>/skills/<name>/ (committed, visible)
//   local     knowledge repo .hl-local/agents/*.md, .hl-local/skills/<name>/ (gitignored, this machine)
// `hl harness sync` writes the winners into the knowledge repo's .claude/agents and .claude/skills (gitignored),
// stamped GENERATED. A hand-made file there (no stamp, no marker) is never touched: it is what the host loads, so it
// is reported as the workspace winner and every source of that name as hidden by it.
import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";
import type { ResolvedItem } from "@helmlock/core";

export type SourceLayer = "system" | "workspace" | "personal" | "local";
export const SOURCE_LAYERS: readonly SourceLayer[] = ["system", "workspace", "personal", "local"];
export type ItemKind = "agent" | "skill";

/** Text every generated agent carries after its frontmatter (also matched by the older copy step's stamp). */
export const GENERATED_MARK = "GENERATED by hl harness sync";
/** Marker file in a generated skill folder. */
export const SKILL_MARKER = ".hl-generated";
export const LOCAL_DIR = ".hl-local";

export interface LayerDir {
  layer: SourceLayer;
  agents: string;
  skills: string;
}

export interface SourceItem {
  kind: ItemKind;
  name: string;
  layer: SourceLayer;
  /** Absolute path: the agent file or the skill folder. */
  abs: string;
  /** The same, relative to the knowledge root with forward slashes. */
  path: string;
  /** A hand-made file in the output folder (.claude/agents or .claude/skills) rather than a layer source. */
  handMade?: boolean;
}

const norm = (p: string) => (process.platform === "win32" ? p.toLowerCase() : p);
const same = (a: string, b: string) => norm(relative(a, b)) === "";
const relPosix = (root: string, p: string) => relative(root, p).split(sep).join("/");
const isDir = (p: string) => {
  try {
    return statSync(p).isDirectory();
  } catch {
    return false;
  }
};
const lf = (s: string) => s.replace(/\r\n/g, "\n");

/** The source folders of each layer, lowest precedence first. Personal needs an author; the delivery repo has system only. */
export function layerDirs(root: string, deliveryRoot: string, author?: string): LayerDir[] {
  const dirs: LayerDir[] = [{ layer: "system", agents: join(deliveryRoot, ".claude", "agents"), skills: join(deliveryRoot, ".claude", "skills") }];
  if (same(root, deliveryRoot)) return dirs;
  dirs.push({ layer: "workspace", agents: join(root, "harness", "agents"), skills: join(root, "harness", "skills") });
  if (author) dirs.push({ layer: "personal", agents: join(root, "people", author, "agents"), skills: join(root, "people", author, "skills") });
  dirs.push({ layer: "local", agents: join(root, LOCAL_DIR, "agents"), skills: join(root, LOCAL_DIR, "skills") });
  return dirs;
}

/** Agent files in a folder: *.md except README.md, by name. */
export function agentFiles(dir: string): { name: string; abs: string }[] {
  if (!isDir(dir)) return [];
  return readdirSync(dir)
    .filter((n) => n.endsWith(".md") && n.toLowerCase() !== "readme.md")
    .sort()
    .map((n) => ({ name: n.slice(0, -3), abs: join(dir, n) }))
    .filter((f) => !isDir(f.abs));
}

/** Skill folders in a folder: subfolders holding a SKILL.md, by name. */
export function skillFolders(dir: string): { name: string; abs: string }[] {
  if (!isDir(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(join(dir, e.name, "SKILL.md")))
    .map((e) => ({ name: e.name, abs: join(dir, e.name) }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export const isGeneratedAgent = (abs: string) => {
  try {
    return readFileSync(abs, "utf8").includes(GENERATED_MARK);
  } catch {
    return false;
  }
};
export const isGeneratedSkill = (folder: string) => existsSync(join(folder, SKILL_MARKER));

/** Every source item in every layer, plus hand-made files in the knowledge repo's output folders. */
export function scanSources(root: string, deliveryRoot: string, author?: string): SourceItem[] {
  const out: SourceItem[] = [];
  for (const d of layerDirs(root, deliveryRoot, author)) {
    for (const f of agentFiles(d.agents)) out.push({ kind: "agent", name: f.name, layer: d.layer, abs: f.abs, path: relPosix(root, f.abs) });
    for (const f of skillFolders(d.skills)) out.push({ kind: "skill", name: f.name, layer: d.layer, abs: f.abs, path: relPosix(root, f.abs) });
  }
  if (!same(root, deliveryRoot)) {
    for (const f of agentFiles(join(root, ".claude", "agents")))
      if (!isGeneratedAgent(f.abs)) out.push({ kind: "agent", name: f.name, layer: "workspace", abs: f.abs, path: relPosix(root, f.abs), handMade: true });
    for (const f of skillFolders(join(root, ".claude", "skills")))
      if (!isGeneratedSkill(f.abs)) out.push({ kind: "skill", name: f.name, layer: "workspace", abs: f.abs, path: relPosix(root, f.abs), handMade: true });
  }
  return out;
}

export interface Resolved {
  kind: ItemKind;
  name: string;
  winner: SourceItem;
  /** Hidden items, highest precedence first. */
  hidden: SourceItem[];
}

const rank = (s: SourceItem) => (s.handMade ? SOURCE_LAYERS.length : SOURCE_LAYERS.indexOf(s.layer));

/** Group by kind and name; the highest layer wins (a hand-made output file outranks every source). */
export function resolveItems(root: string, deliveryRoot: string, author?: string): Resolved[] {
  const groups = new Map<string, SourceItem[]>();
  for (const s of scanSources(root, deliveryRoot, author)) {
    const k = `${s.kind}\0${s.name}`;
    groups.set(k, [...(groups.get(k) ?? []), s]);
  }
  const out: Resolved[] = [];
  for (const items of groups.values()) {
    const sorted = [...items].sort((a, b) => rank(b) - rank(a));
    const [winner, ...hidden] = sorted as [SourceItem, ...SourceItem[]];
    out.push({ kind: winner.kind, name: winner.name, winner, hidden });
  }
  return out.sort((a, b) => a.kind.localeCompare(b.kind) || a.name.localeCompare(b.name));
}

/** The OverridesView rows (GET /api/v1/overrides, `hl overrides`). */
export function toResolvedItems(items: Resolved[]): ResolvedItem[] {
  return items.map((r) => ({
    kind: r.kind,
    name: r.name,
    layer: r.winner.layer,
    path: r.winner.path,
    overrides: r.hidden.map((h) => ({ layer: h.layer, path: h.path })),
  }));
}

export function overridesView(root: string, deliveryRoot: string, author?: string): ResolvedItem[] {
  return toResolvedItems(resolveItems(root, deliveryRoot, author));
}

const sha12 = (s: string | Buffer) => createHash("sha256").update(s).digest("hex").slice(0, 12);

/** Insert a GENERATED note after the YAML frontmatter so the copy still parses as an agent file. */
export function stampAgent(text: string, stamp: string, from = "the system agent", edit = "the delivery repo"): string {
  const t = lf(text);
  const note = `<!-- ${GENERATED_MARK} ${stamp}: a copy of ${from}; edit it in ${edit} -->\n`;
  const m = /^---\n[\s\S]*?\n---\n/.exec(t);
  return m ? `${m[0]}${note}${t.slice(m[0].length)}` : `${note}${t}`;
}

/** The generated .claude/agents/<name>.md for a winning source agent. The stamp hashes the source text. */
export function generatedAgent(item: SourceItem): string {
  const text = lf(readFileSync(item.abs, "utf8"));
  return stampAgent(text, sha12(text), `the ${item.layer} agent ${item.path}`, "that file");
}

/** Files of a skill folder, relative with forward slashes, sorted (the marker is never copied). */
export function skillFiles(folder: string, base = folder): string[] {
  const out: string[] = [];
  for (const e of readdirSync(folder, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const p = join(folder, e.name);
    if (e.isDirectory()) out.push(...skillFiles(p, base));
    else if (!(folder === base && e.name === SKILL_MARKER)) out.push(relPosix(base, p));
  }
  return out;
}

/** The marker text for a generated skill folder: the source path and a hash over its files. */
export function skillMarker(item: SourceItem): string {
  const h = createHash("sha256");
  for (const f of skillFiles(item.abs))
    h.update(`${f}\0`)
      .update(readFileSync(join(item.abs, f)))
      .update("\0");
  return `${GENERATED_MARK} ${h.digest("hex").slice(0, 12)}: a copy of the ${item.layer} skill ${item.path}; edit it there.\n`;
}

/**
 * What sync writes: every winning agent that is not hand-made, and every winning skill above the system layer that is
 * not hand-made (system skills load from the added delivery folder; a project copy is needed only to shadow one).
 */
export function plannedOutputs(items: Resolved[]): { agents: SourceItem[]; skills: SourceItem[] } {
  const agents = items.filter((r) => r.kind === "agent" && !r.winner.handMade).map((r) => r.winner);
  const skills = items.filter((r) => r.kind === "skill" && !r.winner.handMade && r.winner.layer !== "system").map((r) => r.winner);
  return { agents, skills };
}

export type AgentState = "ok" | "stale" | "missing" | "unknown" | "hand-made";

/** Whether .claude/agents/<name>.md holds the current winner (runs warn when it does not). */
export function agentSyncState(root: string, deliveryRoot: string, author: string | undefined, name: string): { state: AgentState; winner?: SourceItem } {
  if (same(root, deliveryRoot)) return { state: "ok" };
  const r = resolveItems(root, deliveryRoot, author).find((x) => x.kind === "agent" && x.name === name);
  if (!r) return { state: "unknown" };
  if (r.winner.handMade) return { state: "hand-made", winner: r.winner };
  const file = join(root, ".claude", "agents", `${name}.md`);
  if (!existsSync(file)) return { state: "missing", winner: r.winner };
  return { state: lf(readFileSync(file, "utf8")) === generatedAgent(r.winner) ? "ok" : "stale", winner: r.winner };
}

/**
 * A one-line notice for a run with --agent, or undefined when the agent is in sync. Silent in a repo without a
 * harness source (harness/harness.toml): `hl harness sync` cannot run there, so there is nothing to suggest.
 */
export function agentNotice(root: string, deliveryRoot: string, author: string | undefined, name: string): string | undefined {
  if (!existsSync(join(root, "harness", "harness.toml"))) return undefined;
  let s: ReturnType<typeof agentSyncState>;
  try {
    s = agentSyncState(root, deliveryRoot, author, name);
  } catch {
    return undefined;
  }
  switch (s.state) {
    case "unknown":
      return `[hl] agent "${name}" is in no layer (system, workspace, personal, local); the host may not find it`;
    case "missing":
      return `[hl] agent "${name}" (${s.winner?.layer}: ${s.winner?.path}) is not in .claude/agents yet; run \`hl harness sync\``;
    case "stale":
      return `[hl] .claude/agents/${name}.md is out of date with ${s.winner?.layer}: ${s.winner?.path}; run \`hl harness sync\``;
    default:
      return undefined;
  }
}
