// shared/INDEX.md (F116): one line per document under shared/ and projects/*/wiki/, so agents find reference
// without loading it. Title from the first heading, summary from the first paragraph. Generated; never hand-edited.
import type { Context, KnowledgeView } from "@helmlock/core";

export const INDEX_FILE = "shared/INDEX.md";
export type IndexEntry = KnowledgeView["index"][number];
const MAX_SUMMARY = 160;

export function kindOf(path: string): IndexEntry["kind"] {
  const p = path.toLowerCase();
  if (p.startsWith("shared/digests/")) return "digest";
  if (p.startsWith("shared/templates/")) return "template";
  if (p.startsWith("shared/checklists/")) return "checklist";
  if (/\/decisions\//.test(p)) return "decision";
  if (/\/runbooks\//.test(p)) return "runbook";
  if (/\/standards\//.test(p)) return "standard";
  if (/(^|\/)glossary\.md$/.test(p)) return "glossary";
  if (p.startsWith("shared/wiki/") || /^projects\/[^/]+\/wiki\//.test(p)) return "wiki";
  return "other";
}

const plain = (s: string) =>
  s
    .replace(/\[\[([^\]|]*\|)?([^\]]*)\]\]/g, "$2")
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/[*_`]+/g, "")
    .replace(/\s+/g, " ")
    .trim();

/** Title (first `# ` heading, else the file name) and the first prose paragraph, one line. */
export function describe(path: string, text: string): { title: string; summary: string } {
  let body = text.replace(/^\uFEFF/, "").replace(/\r\n/g, "\n");
  const fm = /^---\n[\s\S]*?\n---\n?/.exec(body);
  if (fm) body = body.slice(fm[0].length);
  const lines = body.split("\n");
  let title: string | undefined;
  const para: string[] = [];
  let inCode = false;
  for (const raw of lines) {
    const line = raw.trim();
    if (line.startsWith("```")) {
      inCode = !inCode;
      continue;
    }
    if (inCode) continue;
    const h = /^(#{1,6})\s+(.+)$/.exec(line);
    if (h) {
      if (!title && h[1] === "#") title = plain(h[2] as string);
      if (para.length) break;
      continue;
    }
    if (!line) {
      if (para.length) break;
      continue;
    }
    if (/^(<!--|\|?\s*-{3,}|>?\s*$)/.test(line)) continue;
    para.push(line.replace(/^>\s?/, "").replace(/^[-*+]\s+/, ""));
  }
  let summary = plain(para.join(" "));
  if (summary.length > MAX_SUMMARY) summary = `${summary.slice(0, MAX_SUMMARY - 3).replace(/\s+\S*$/, "")}...`;
  return { title: title ?? (path.split("/").pop() as string).replace(/\.md$/, ""), summary };
}

export async function collectIndex(ctx: Context): Promise<IndexEntry[]> {
  const files = ctx.get("files");
  const paths = new Set([...(await files.list("shared/**/*.md")), ...(await files.list("projects/*/wiki/**/*.md"))]);
  paths.delete(INDEX_FILE);
  const out: IndexEntry[] = [];
  for (const path of [...paths].sort()) {
    const { title, summary } = describe(path, await files.readText(path));
    out.push({ path, title, summary, kind: kindOf(path) });
  }
  return out;
}

export function renderIndex(entries: IndexEntry[]): string {
  const head = [
    "# Shared index (generated by hl, do not edit)",
    "",
    "One line per document in `shared/` and `projects/*/wiki/`. Rebuild with `hl index build`. Read a document only when the task needs it.",
    "",
  ];
  const lines = entries.map((e) => `- \`${e.path}\` (${e.kind}) **${e.title}**${e.summary ? `: ${e.summary}` : ""}`);
  return `${[...head, ...(lines.length ? lines : ["(no documents yet)"])].join("\n")}\n`;
}

export async function buildIndex(ctx: Context, o: { dryRun?: boolean } = {}): Promise<{ entries: IndexEntry[]; changed: boolean; path: string }> {
  const files = ctx.get("files");
  const entries = await collectIndex(ctx);
  const text = renderIndex(entries);
  const same = (await files.exists(INDEX_FILE)) && (await files.readText(INDEX_FILE)) === text;
  if (!same && !o.dryRun) await files.writeText(INDEX_FILE, text);
  return { entries, changed: !same, path: INDEX_FILE };
}
